import { useEffect, useMemo, useState } from 'react';
import { adminApiBase, clearAdminToken, createAdmin, deleteAdmin, getAdmin, getAdminToken, hasAdminApi, loginAdmin, updateAdmin, updateWorkflow, uploadImage } from './api/admin.js';

const modules = [
  ['solution-groups', '方案二级标题'], ['solutions', '解决方案'], ['news-categories', '新闻分类'], ['news', '新闻'], ['cases', '案例'], ['help-categories', '帮助分类'], ['help', '帮助中心'], ['leads', '合作线索'], ['tickets', '技术工单'],
];
const blankSolution = { group_id: '', name: '', slug: '', icon: '', cover_image: '', summary: '', sort_order: 0, published: false, detail: {} };
const blankContent = { category: '', title: '', slug: '', summary: '', body: '', image_url: '', featured: false, published: false, sort_order: 0 };

const detailKeys = ['hero', 'capabilities', 'architecture', 'advantages', 'scenarios', 'flow', 'faq', 'cta'];
const parseValue = (item) => ({ ...item, detail: item.detail ?? Object.fromEntries(detailKeys.filter(key => key in item).map(key => [key, item[key]])) });
function Field({ label, children }) { return <label className="admin-field"><span>{label}</span>{children}</label>; }
function Message({ value }) { return value ? <p className="admin-message">{value}</p> : null; }

function AdminLogin({ onLoggedIn }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); setMessage(''); try { await loginAdmin({ username, password }); onLoggedIn(); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  return <main className="admin-shell"><form className="admin-login" onSubmit={submit}><p>NEXA / 运营</p><h1>管理员登录</h1><span>请使用部署环境中配置的管理员账号访问内容工作台。</span><input value={username} onChange={e => setUsername(e.target.value)} placeholder="用户名" autoComplete="username" required/><input value={password} onChange={e => setPassword(e.target.value)} placeholder="密码" autoComplete="current-password" type="password" required/><button className="button green" disabled={loading}>{loading ? '正在登录…' : '登录后台'}</button><Message value={message}/></form></main>;
}

function ImageUpload({ onUploaded }) {
  const [message, setMessage] = useState(''); const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setMessage('正在上传…'); try { const result = await uploadImage(file); onUploaded(`${adminApiBase}${result.url}`); setMessage('上传完成，已填入封面图地址。'); } catch (error) { setMessage(error.message); } finally { event.target.value = ''; } };
  return <div className="image-upload"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload}/><small>JPG、PNG、WebP 或 GIF，最大 10MB。</small><Message value={message}/></div>;
}

function SolutionEditor({ groups, selected, onSave, onDelete }) {
  const [value, setValue] = useState(blankSolution); const [message, setMessage] = useState('');
  useEffect(() => setValue(selected ? parseValue(selected) : blankSolution), [selected]);
  const set = (key, next) => setValue(current => ({ ...current, [key]: next }));
  const save = async (event) => { event.preventDefault(); try { const detail = typeof value.detail === 'string' ? JSON.parse(value.detail || '{}') : value.detail; await onSave({ ...value, group_id: Number(value.group_id), sort_order: Number(value.sort_order), detail }); setMessage('方案已保存。'); } catch (error) { setMessage(error instanceof SyntaxError ? '详情 JSON 格式不正确。' : error.message); } };
  return <form className="admin-editor" onSubmit={save}><div className="editor-head"><h2>{selected ? '编辑行业方案' : '新建行业方案'}</h2><small>详情数据会由前端固定模板渲染。</small></div><div className="admin-form-grid"><Field label="所属二级标题"><select value={value.group_id} onChange={e => set('group_id', e.target.value)} required><option value="">请选择</option>{groups.map(group => <option key={group.id} value={group.id}>{group.name}</option>)}</select></Field><Field label="行业名称"><input value={value.name} onChange={e => set('name', e.target.value)} required /></Field><Field label="slug"><input value={value.slug} onChange={e => set('slug', e.target.value)} pattern="[a-z0-9-]+" required /></Field><Field label="图标"><input value={value.icon} onChange={e => set('icon', e.target.value)} /></Field><Field label="封面图 URL"><input value={value.cover_image} onChange={e => set('cover_image', e.target.value)} /></Field><Field label="上传封面图"><ImageUpload onUploaded={url => set('cover_image', url)}/></Field><Field label="排序"><input type="number" value={value.sort_order} onChange={e => set('sort_order', e.target.value)} /></Field><Field label="简介"><textarea value={value.summary} onChange={e => set('summary', e.target.value)} rows="3" /></Field><Field label="详情内容 JSON"><textarea className="code-input" value={typeof value.detail === 'string' ? value.detail : JSON.stringify(value.detail, null, 2)} onChange={e => set('detail', e.target.value)} rows="16" /></Field></div><label className="check"><input type="checkbox" checked={value.published} onChange={e => set('published', e.target.checked)} />已发布</label><div className="editor-actions"><button className="button green">保存方案</button>{selected && <button type="button" className="text-danger" onClick={() => onDelete(selected.id)}>删除方案</button>}</div><Message value={message} /></form>;
}

function ContentEditor({ kind, selected, onSave, onDelete }) {
  const [value, setValue] = useState(blankContent); const [message, setMessage] = useState('');
  useEffect(() => setValue(selected ? { ...blankContent, ...selected } : blankContent), [selected]);
  const set = (key, next) => setValue(current => ({ ...current, [key]: next }));
  const save = async (event) => { event.preventDefault(); try { await onSave({ ...value, sort_order: Number(value.sort_order) }); setMessage('内容已保存。'); } catch (error) { setMessage(error.message); } };
  return <form className="admin-editor" onSubmit={save}><div className="editor-head"><h2>{selected ? '编辑内容' : '新建内容'}</h2><small>{kind === 'help' ? '可设为热门操作指南。' : kind === 'cases' ? '发布且设为首页精选后，会显示在首页「项目现场与行业实践」。' : '发布后将可由前台读取。'}</small></div>{kind === 'cases' && <section className="case-image-editor"><div><b>首页案例图片</b><small>首页卡片使用此图片；可粘贴图片地址或从电脑上传。</small></div><div className="case-image-fields"><Field label="案例图片 URL"><input value={value.image_url ?? ''} onChange={e => set('image_url', e.target.value)} placeholder="https://… 或上传后自动填入" /></Field><Field label="上传案例图片"><ImageUpload onUploaded={url => set('image_url', url)}/></Field></div></section>}<div className="admin-form-grid"><Field label="标题"><input value={value.title} onChange={e => set('title', e.target.value)} required /></Field><Field label="slug"><input value={value.slug} onChange={e => set('slug', e.target.value)} pattern="[a-z0-9-]+" required /></Field><Field label="分类"><input value={value.category ?? ''} onChange={e => set('category', e.target.value)} /></Field><Field label="排序"><input type="number" value={value.sort_order} onChange={e => set('sort_order', e.target.value)} /></Field><Field label="摘要"><textarea value={value.summary} onChange={e => set('summary', e.target.value)} rows="3" /></Field><Field label="正文"><textarea value={value.body} onChange={e => set('body', e.target.value)} rows="12" /></Field></div><div className="check-row"><label className="check"><input type="checkbox" checked={value.published} onChange={e => set('published', e.target.checked)} />已发布</label><label className="check"><input type="checkbox" checked={value.featured} onChange={e => set('featured', e.target.checked)} />首页精选 / 热门</label></div><div className="editor-actions"><button className="button green">保存内容</button>{selected && <button type="button" className="text-danger" onClick={() => onDelete(selected.id)}>删除内容</button>}</div><Message value={message} /></form>;
}

function GroupEditor({ selected, onSave, onDelete }) {
  const [value, setValue] = useState({ name: '', sort_order: 0, published: true }); const [message, setMessage] = useState('');
  useEffect(() => setValue(selected ? { name: selected.name, sort_order: selected.sort_order, published: selected.published } : { name: '', sort_order: 0, published: true }), [selected]);
  const save = async (event) => { event.preventDefault(); try { await onSave({ ...value, sort_order: Number(value.sort_order) }); setMessage('二级标题已保存。'); } catch (error) { setMessage(error.message); } };
  return <form className="admin-editor" onSubmit={save}><div className="editor-head"><h2>{selected ? '编辑二级标题' : '新建二级标题'}</h2><small>仅用于 Header「解决方案」与方案总览的分组展示。</small></div><div className="admin-form-grid"><Field label="名称"><input value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} required /></Field><Field label="排序"><input type="number" value={value.sort_order} onChange={e => setValue({ ...value, sort_order: e.target.value })} /></Field></div><label className="check"><input type="checkbox" checked={value.published} onChange={e => setValue({ ...value, published: e.target.checked })} />已发布</label><div className="editor-actions"><button className="button green">保存二级标题</button>{selected && <button type="button" className="text-danger" onClick={() => onDelete(selected.id)}>删除二级标题</button>}</div><Message value={message} /></form>;
}

function CategoryEditor({ selected, onSave, onDelete }) {
  const [value, setValue] = useState({ name: '', slug: '', sort_order: 0, published: true }); const [message, setMessage] = useState('');
  useEffect(() => setValue(selected ? { name: selected.name, slug: selected.slug, sort_order: selected.sort_order, published: selected.published } : { name: '', slug: '', sort_order: 0, published: true }), [selected]);
  const save = async (event) => { event.preventDefault(); try { await onSave({ ...value, sort_order: Number(value.sort_order) }); setMessage('分类已保存。'); } catch (error) { setMessage(error.message); } };
  return <form className="admin-editor" onSubmit={save}><div className="editor-head"><h2>{selected ? '编辑分类' : '新建分类'}</h2><small>分类用于新闻或帮助中心的内容筛选。</small></div><div className="admin-form-grid"><Field label="名称"><input value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} required /></Field><Field label="slug"><input value={value.slug} onChange={e => setValue({ ...value, slug: e.target.value })} pattern="[a-z0-9-]+" required /></Field><Field label="排序"><input type="number" value={value.sort_order} onChange={e => setValue({ ...value, sort_order: e.target.value })} /></Field></div><label className="check"><input type="checkbox" checked={value.published} onChange={e => setValue({ ...value, published: e.target.checked })} />已发布</label><div className="editor-actions"><button className="button green">保存分类</button>{selected && <button type="button" className="text-danger" onClick={() => onDelete(selected.id)}>删除分类</button>}</div><Message value={message} /></form>;
}

function SubmissionList({ title, items, kind, onSave }) { const [editing, setEditing] = useState(null); const [value, setValue] = useState({ workflow_status: '待处理', assignee: '', notes: '' }); const open = (item) => { setEditing(item.id); setValue({ workflow_status: item.workflow_status || '待处理', assignee: item.assignee || '', notes: item.notes || '' }); }; const save = async () => { await onSave(editing, value); setEditing(null); }; return <section className="admin-editor"><div className="editor-head"><h2>{title}</h2><small>可记录处理状态、负责人和内部备注。</small></div>{items.length ? <div className="submission-list">{items.map(item => <article key={item.id}><b>{item.company} · {item.name}</b><span>{item.type}{item.level ? ` / ${item.level}` : ''} · {item.workflow_status || '待处理'}</span><p>{item.description}</p><small>{item.contact} · {item.created_at}</small>{editing === item.id ? <div className="workflow-editor"><select value={value.workflow_status} onChange={e => setValue({ ...value, workflow_status: e.target.value })}>{['待处理', '处理中', '已完成'].map(x => <option key={x}>{x}</option>)}</select><input value={value.assignee} onChange={e => setValue({ ...value, assignee: e.target.value })} placeholder="负责人"/><textarea value={value.notes} onChange={e => setValue({ ...value, notes: e.target.value })} placeholder="内部备注" rows="3"/><button className="button green" onClick={save}>保存流转</button></div> : <button className="workflow-link" onClick={() => open(item)}>更新处理状态</button>}</article>)}</div> : <p className="empty-admin">暂无提交数据。</p>}</section>; }

export default function Admin() {
  const [active, setActive] = useState('solutions'); const [groups, setGroups] = useState([]); const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [status, setStatus] = useState(''); const [authenticated, setAuthenticated] = useState(Boolean(getAdminToken()));
  const endpointFor = (kind) => ({ 'news-categories': 'categories/news/items', 'help-categories': 'categories/help/items' }[kind] ?? kind);
  const load = async (kind = active) => { if (!hasAdminApi || !authenticated) return; setStatus('正在读取…'); try { const [nextItems, nextGroups] = await Promise.all([getAdmin(endpointFor(kind)), kind === 'solutions' ? getAdmin('solution-groups') : Promise.resolve(groups)]); setItems(nextItems); if (kind === 'solutions') setGroups(nextGroups); setStatus(''); } catch (error) { if (error.message.includes('登录')) { clearAdminToken(); setAuthenticated(false); } setStatus(error.message); } };
  useEffect(() => { setSelected(null); load(active); }, [active, authenticated]);
  const save = async (payload) => { const path = endpointFor(active); const result = selected ? updateAdmin(`${path}/${selected.id}`, payload) : createAdmin(path, payload); await result; await load(); };
  const remove = async (id) => { if (!confirm('确定删除这条内容吗？')) return; await deleteAdmin(`${endpointFor(active)}/${id}`); setSelected(null); await load(); };
  const title = useMemo(() => modules.find(([id]) => id === active)?.[1], [active]);
  if (!hasAdminApi) return <main className="admin-shell"><section className="admin-api-needed"><h1>运营后台需要 API 连接</h1><p>在 <code>front/.env.local</code> 中设置 <code>VITE_API_BASE_URL</code>，例如 <code>http://localhost:8000</code>。</p></section></main>;
  if (!authenticated) return <AdminLogin onLoggedIn={() => setAuthenticated(true)}/>;
  const readonly = active === 'leads' || active === 'tickets';
  const isCategory = active.endsWith('-categories');
  return <main className="admin-shell"><aside className="admin-sidebar"><a className="admin-logo" href="#/">NEXA / 运营</a><p>内容工作台</p>{modules.map(([id, label]) => <button className={active === id ? 'active' : ''} key={id} onClick={() => setActive(id)}>{label}</button>)}<button className="admin-logout" onClick={() => { clearAdminToken(); setAuthenticated(false); }}>退出登录</button></aside><section className="admin-main"><header className="admin-top"><div><p>运营管理</p><h1>{title}</h1></div>{!readonly && <button className="button dark" onClick={() => setSelected(null)}>新建{active === 'solutions' ? '方案' : active === 'solution-groups' ? '二级标题' : isCategory ? '分类' : '内容'}</button>}</header>{status && <p className="admin-message">{status}</p>}<div className="admin-workspace"><section className="admin-list">{items.map(item => <button className={selected?.id === item.id ? 'selected' : ''} key={item.id} onClick={() => setSelected(item)}><b>{item.name ?? item.title ?? item.company}</b><span>{item.published === false ? '未发布' : item.category ?? item.type ?? '已发布'}</span></button>)}{!items.length && !status && <p className="empty-admin">暂无内容。点击右上角开始创建。</p>}</section>{readonly ? <SubmissionList title={title} items={items} kind={active} onSave={async (id, payload) => { await updateWorkflow(active, id, payload); await load(); }} /> : active === 'solution-groups' ? <GroupEditor selected={selected} onSave={save} onDelete={remove} /> : isCategory ? <CategoryEditor selected={selected} onSave={save} onDelete={remove} /> : active === 'solutions' ? <SolutionEditor groups={groups} selected={selected} onSave={save} onDelete={remove} /> : <ContentEditor kind={active} selected={selected} onSave={save} onDelete={remove} />}</div></section></main>;
}
